spring:
  application:
    name: career-service
  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    vault:
      uri: http://localhost:8200
      token: DayanaChinchin-examen
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
      application-name: career-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka